#:schema node_modules/wrangler/config-schema.json
name = "banglacode-docs"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[build]
command = "npm run build:cf"

[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true
